#!/bin/bash
owner=$(stat -c '%U' hello)
if [ "$owner" = "guillaume" ]; then
  chown betty hello
  echo "Owner of file 'hello' changed to 'betty' because it was owned by 'guillaume'."
else
  echo "Cannot change owner of file 'hello' to 'betty' because it is not owned by 'guillaume'."
fii
